Repository fog/fog-kubevirt, pull requests merged in 2019-01, with the labels that each got.

#59 Change registry to container disk
  fog-kubevirt.gemspec
  lib/fog/compute/kubevirt/models/vm_data.rb
  lib/fog/compute/kubevirt/models/vms.rb
  lib/fog/compute/kubevirt/requests/get_vminstance.rb
  lib/fog/compute/kubevirt/requests/list_vms.rb
Labels: bug

#63 Change kubevirt api version
  lib/fog/compute/kubevirt.rb
  lib/fog/compute/kubevirt/models/vms.rb
  lib/fog/compute/kubevirt/requests/create_vm.rb
  spec/compute_v1alpha2_spec.rb
  spec/fixtures/kubevirt/networkattachmentdefinition/networkattachmentdefinitions_crud.yml
  spec/fixtures/kubevirt/networkattachmentdefinition/v1alpha2/networkattachmentdefinitions_crud.yml
  spec/fixtures/kubevirt/pvc/pvcs_crud.yml
  spec/fixtures/kubevirt/pvc/v1alpha2/pvcs_crud.yml
  spec/fixtures/kubevirt/service/services_crud.yml
  spec/fixtures/kubevirt/service/v1alpha2/services_crud.yml
  spec/fixtures/kubevirt/volume/v1alpha2/volumes_crud.yml
  spec/fixtures/kubevirt/volume/volumes_crud.yml
  spec/network_attachment_definition_v1alpha2_spec.rb
  spec/pvcs_v1alpha2_spec.rb
  spec/shared_context.rb
  spec/volumes_v1alpha2_spec.rb
Labels: bug

#64 Change kubevirt api version
  lib/fog/kubevirt/compute/compute.rb
  lib/fog/kubevirt/compute/models/vms.rb
  lib/fog/kubevirt/compute/requests/create_vm.rb
  spec/compute_v1alpha2_spec.rb
  spec/fixtures/kubevirt/networkattachmentdefinition/networkattachmentdefinitions_crud.yml
  spec/fixtures/kubevirt/networkattachmentdefinition/v1alpha2/networkattachmentdefinitions_crud.yml
  spec/fixtures/kubevirt/pvc/pvcs_crud.yml
  spec/fixtures/kubevirt/pvc/v1alpha2/pvcs_crud.yml
  spec/fixtures/kubevirt/service/services_crud.yml
  spec/fixtures/kubevirt/service/v1alpha2/services_crud.yml
  spec/fixtures/kubevirt/volume/v1alpha2/volumes_crud.yml
  spec/fixtures/kubevirt/volume/volumes_crud.yml
  spec/network_attachment_definition_v1alpha2_spec.rb
  spec/pvcs_v1alpha2_spec.rb
  spec/shared_context.rb
  spec/volumes_v1alpha2_spec.rb
Labels: bug

#58 Make VmVolume a Fog model
  CHANGELOG.md
  lib/fog/kubevirt/version.rb
Labels: merge to master, wip

#70 Watch VMIs
  lib/fog/kubevirt/compute/compute.rb
Labels: bug

#74 Fix broken vm creation
  lib/fog/compute/kubevirt/models/vms.rb
Labels: merge to master

#72 Backport: Introduce config file based client
  lib/fog/compute/kubevirt.rb
Labels: enhancement

#75 Core 1.45.0 vm volume
  lib/fog/compute/kubevirt/models/vm_base.rb
  lib/fog/compute/kubevirt/models/vm_data.rb
Labels: merge to master
